import { Building, FacadeMaterial, LightSource } from './types';

export const sampleMaterials: FacadeMaterial[] = [
  {
    id: 'glass-clear',
    name: '透明玻璃',
    reflectivity: 0.15,
    emissivity: 0.85,
    color: '#87CEEB',
    category: 'glass',
  },
  {
    id: 'glass-reflective',
    name: '反光玻璃',
    reflectivity: 0.7,
    emissivity: 0.3,
    color: '#708090',
    category: 'glass',
  },
  {
    id: 'concrete-gray',
    name: '灰色混凝土',
    reflectivity: 0.25,
    emissivity: 0.9,
    color: '#A9A9A9',
    category: 'concrete',
  },
  {
    id: 'concrete-white',
    name: '白色混凝土',
    reflectivity: 0.6,
    emissivity: 0.85,
    color: '#F5F5F5',
    category: 'concrete',
  },
  {
    id: 'metal-stainless',
    name: '不锈钢',
    reflectivity: 0.6,
    emissivity: 0.4,
    color: '#C0C0C0',
    category: 'metal',
  },
  {
    id: 'metal-aluminum',
    name: '铝合金',
    reflectivity: 0.7,
    emissivity: 0.3,
    color: '#D3D3D3',
    category: 'metal',
  },
  {
    id: 'stone-granite',
    name: '花岗岩',
    reflectivity: 0.3,
    emissivity: 0.9,
    color: '#696969',
    category: 'stone',
  },
  {
    id: 'wood-cedar',
    name: '雪松木材',
    reflectivity: 0.15,
    emissivity: 0.9,
    color: '#8B4513',
    category: 'wood',
  },
];

export const sampleBuildings: Building[] = [
  {
    id: 'building-001',
    name: '商业中心A座',
    x: 20,
    y: 20,
    width: 15,
    height: 15,
    floors: 30,
    facadeMaterial: sampleMaterials[1],
  },
  {
    id: 'building-002',
    name: '办公大楼B',
    x: 50,
    y: 30,
    width: 20,
    height: 20,
    floors: 25,
    facadeMaterial: sampleMaterials[0],
  },
  {
    id: 'building-003',
    name: '住宅区C栋',
    x: 70,
    y: 60,
    width: 12,
    height: 12,
    floors: 15,
    facadeMaterial: sampleMaterials[2],
  },
  {
    id: 'building-004',
    name: '购物中心D',
    x: 15,
    y: 70,
    width: 25,
    height: 18,
    floors: 8,
    facadeMaterial: sampleMaterials[4],
  },
  {
    id: 'building-005',
    name: '酒店E',
    x: 60,
    y: 80,
    width: 18,
    height: 16,
    floors: 20,
    facadeMaterial: sampleMaterials[1],
  },
];

export const sampleLightSources: LightSource[] = [
  {
    id: 'light-001',
    x: 35,
    y: 35,
    intensity: 1.0,
    wavelength: 580,
    type: 'streetlight',
  },
  {
    id: 'light-002',
    x: 55,
    y: 45,
    intensity: 1.2,
    wavelength: 550,
    type: 'building',
  },
  {
    id: 'light-003',
    x: 25,
    y: 80,
    intensity: 0.8,
    wavelength: 600,
    type: 'advertisement',
  },
  {
    id: 'light-004',
    x: 80,
    y: 70,
    intensity: 1.5,
    wavelength: 500,
    type: 'building',
  },
  {
    id: 'light-005',
    x: 65,
    y: 85,
    intensity: 1.0,
    wavelength: 580,
    type: 'streetlight',
  },
  {
    id: 'light-006',
    x: 10,
    y: 50,
    intensity: 0.9,
    wavelength: 550,
    type: 'streetlight',
  },
];
